# Generated by Django 3.2.16 on 2022-12-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha Publicación')),
                ('picture', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True, verbose_name='Activo/No Activo')),
                ('duration', models.IntegerField(max_length=5, verbose_name='duración del album')),
                ('tracklist', models.CharField(max_length=300, verbose_name='URL del tracklist')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha Publicación')),
                ('picture', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True, verbose_name='Activo/No Activo')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha Publicación')),
                ('picture', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True, verbose_name='Activo/No Activo')),
                ('link', models.CharField(max_length=300, verbose_name='URL de la canción')),
                ('duration', models.IntegerField(max_length=5, verbose_name='duración del album')),
                ('type', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deezer.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deezer.artist')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deezer.artist'),
        ),
    ]
