# Generated by Django 3.2.16 on 2022-12-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deezer', '0002_auto_20221228_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
