# Generated by Django 3.2.16 on 2022-12-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deezer', '0003_alter_song_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='duration',
        ),
    ]
